name: weisro
description: A new Flutter project.

publish_to: "none"

version: 1.1.4+6

environment:
  sdk: "^3.5.4"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: null
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  flutter_gallery_3d: ^1.1.1
  smooth_page_indicator: ^1.2.0+3
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  pinput: ^5.0.0
  device_preview: ^1.2.0
  dio: ^5.7.0
  cached_network_image: ^3.3.1
  dartz: ^0.10.1
  shimmer: ^3.0.0
  shared_preferences: ^2.2.3
  meta: ^1.9.1
  html: ^0.15.4
  logger: ^2.4.0
  get_it: ^8.0.2
  intl_phone_field: ^3.2.0
  country_code_picker: ^3.1.0
  image_picker: ^1.0.8
  image: ^4.3.0
  loading_animation_widget: ^1.3.0
  dropdown_search: ^6.0.1
  day_night_time_picker: ^1.3.1
  lottie: ^3.1.3
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  awesome_snackbar_content: ^0.1.4
  quick_actions: ^1.1.0
  home_widget: ^0.7.0
  animated_rating_stars: ^1.0.1
  flutter_html: ^3.0.0-beta.2
  upgrader: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  bloc_test: ^9.1.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Medium.ttf
          weight: 500

flutter_assets:
  assets_path: assets/images
  output_path: lib/core/assets_path/
  filename: image_path.dart
  field_prefix: null
  classname: ImagePath
# flutter_intl:
#   enabled: true

# flutter_assets:
#   assets_path: assets/icons
#   output_path: lib/core/assets_path/
#   filename: icons_path.dart
#   field_prefix: null
#   classname: IconsPath
flutter_intl:
  enabled: true
